version: '3'
services:
  mango1:
    image: server
    environment:
      - APP=golumolu
    ports:
      - "8081:5000"
  mango2:
    image: server
    environment:
      - APP=golumolu
    ports:
      - "8082:5000"
  apple1:
    image: server
    environment:
      - APP=hello
    ports:
      - "9081:5000"
  apple2:
    image: server
    environment:
      - APP=hello
    ports:
      - "9082:5000"